name: UI Tests

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - run: npm ci
      - run: npx playwright install chromium
      - run: npm install -g allure-commandline --save-dev

  test:
    runs-on: ubuntu-latest
    needs: build
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - run: npm ci
      - run: npx playwright install chromium

      - name: Clean previous Allure results
        run: rm -rf ./allure-results

      - name: Run Playwright tests
        run: npx playwright test src/ui/tests
        env:
          BASE_UI_URL: https://www.discogs.com/
          BASE_URL: https://api.discogs.com/
          USER_NAME: ${{ secrets.USER_NAME }}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
          LABEL_ID: '681346'

      - name: Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: ./allure-results

  report:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - run: npm install -g allure-commandline --save-dev

      - name: Download Allure Results
        uses: actions/download-artifact@v4
        with:
          name: allure-results
          path: ./allure-results

      - name: Generate Allure Report
        run: allure generate ./allure-results --clean -o ./allure-report

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          publish_branch: allure-report
          force_orphan: true

      - name: Print Allure Report URL
        run: echo "View report:https://artemguschin8876.github.io/discogs-api-tests/index.html"
